### ISSUE TITLE
Imod -- Fiducial alignment step 

### ISSUE THREAD

**Issue by DmitrySemchonok** [scipion-em/scipion-em-imod#129]
Following the manual https://docs.google.com/document/d/1ESIGTwPyunnelq4zCVrSL1BSqn-Qpf0tCcN-vY_mCtk/edit#
I got the error when the “Generate Interpolated tilt-series” was enabled in Protocol Imod: Fiducial alignment.  When this option is disabled, the protocol runs fine.

Does anyone know the reason?

Kind regards,
Dmitry

**Comment by fede-pe** [comment]
Hello Dimitry! What mistake are you getting?

**Comment by azazellochg** [comment]
@DmitrySemchonok No error message provided. Please reopen if necessary.
