### ISSUE TITLE
generate fiducial model stucks when executing

### ISSUE THREAD

**Issue by fede-pe** [scipion-em/scipion-em-imod#156]
The protocol gets stuck when running autofidseed program (in generateFiducialSeedStep). In particular, it stucks when running beadtrack  for the central views of the tilt image.

**Comment by azazellochg** [comment]
1) will need to see full output logs
2) can you reproduce it with etomo outside scipion? If yes, then this is not scipion problem

**Comment by fede-pe** [comment]
[run.stdout.txt](https://github.com/scipion-em/scipion-em-imod/files/10001881/run.stdout.txt)
1. I attached the logs
2. I processed this data without this problem inside scipion on 2022-11-07, so there must be related to some change since that date. Also, I am not able to reproduce the error with etomo inside scipion. I can install imod on a different machine and try with the same data if needed (now I am working on a server)

**Comment by azazellochg** [comment]
Hi, thank you for the log file.
Are you able to share the failing tilt-series (tsp_65)? How was it obtained? Any preprocessing / filtering?

**Comment by azazellochg** [comment]
Found 
```
ERROR: BEADTRACK - Reading image file
ERROR: iiInitReadSectionAny - Specification of area to read (x 2147483562 to 1853 y 2147483562 to 1919) is incorrect
``` in the log for tsp53.

**Comment by azazellochg** [comment]
```
ERROR: autofidseed - Running beadtrack with seed from view 20
ERROR: BEADTRACK - There must be 2 or 4 values entered for ShiftsNearZeroTilt
ERROR: autofidseed - beadtrack -StandardInput: exited with status 1
```
tsp24

**Comment by azazellochg** [comment]
ok, tons of errors actually. Can you share Runs/004846_ProtImodFiducialModel/extra/tsp_12/tsp_12_track.com file?

**Comment by azazellochg** [comment]
The problem appears to be with image processing, not the plugin.
