### ISSUE TITLE
ERROR! Required library l was not found

### ISSUE THREAD

**Issue by wlugmayr** [scipion-em/scipion-em-imod#179]
scipion3 installp -p . --devel
Scipion v3.0.13 - Eugenius
Building scipion-em-imod ...
/gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/miniconda/envs/scipion3/bin/python -m pip install -e .
Obtaining file:///gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/devel/scipion-em-imod
  Preparing metadata (setup.py) ... done
Installing collected packages: scipion-em-imod
  Attempting uninstall: scipion-em-imod
    Found existing installation: scipion-em-imod 3.1.2
    Uninstalling scipion-em-imod-3.1.2:
      Successfully uninstalled scipion-em-imod-3.1.2
  Running setup.py develop for scipion-em-imod
Successfully installed scipion-em-imod-3.1.2
Done (11.70 seconds)
Building jpeg ...
  All targets exist, skipping.
Done (0.00 seconds)
Building imod-4.11.20 ...
  Skipping command: wget -nv -c -O /gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/software/em/void.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/em/void.tgz
mv -v /gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/software/em/void.tgz.part /gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/software/em/void.tgz
  All targets exist.
  Skipping command: mkdir /gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/software/em/imod-4.11.20
  All targets exist.
cd /gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/software/em/imod-4.11.20
echo "ERROR! Required library l was not found. Please consider to install it (sudo apt-get install in Ubuntu, sudo yum install in centOS, etc)." && exit 1
ERROR! Required library l was not found. Please consider to install it (sudo apt-get install in Ubuntu, sudo yum install in centOS, etc).
target '/gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/software/em/imod-4.11.20/l' not built (after running 'echo "ERROR! Required library l was not found. Please consider to install it (sudo apt-get install in Ubuntu, sudo yum install in centOS, etc)." && exit 1')

**Comment by wlugmayr** [comment]
I did by hand:
cd /gpfs/cssb/software/centos7/x86_64/scipion/3.0-tomo/software/em/imod-4.11.20
wget --continue http://bio3d.colorado.edu/imod/AMD64-RHEL5/imod_4.11.20_RHEL7-64_CUDA10.1.sh --no-check-certificate
sh imod_4.11.20_RHEL7-64_CUDA10.1.sh -dir . -yes -skip
touch imod_4.11.20_installed

and added to scipion.conf:
IMOD_HOME = %(EM_ROOT)s/imod-4.11.20/IMOD
this seems to work.

I think the error is somewhere when checking the install dependencies.

**Comment by pconesa** [comment]
Yes, it a bug in the installer that will be fixed i the next release of scipion-app.  Thanks.
