### ISSUE TITLE
scipion-em-aretomo -outImod generates one extra blank line on the xf

### ISSUE THREAD

**Issue by plosana** [scipion-em/scipion-em-imod#184]
I am trying to align the Tilt Series with aretomo, and import those alignments to imod. If you use the command `-outImod 1` in additional parameters, it generates, per Tilt Series, an additional folder with all the elements that etomo would generate.
However, when I try to import the matrix with imod - Import transformation matrix, it fails:
![image](https://user-images.githubusercontent.com/8470316/217265942-9d56fef9-1d46-4f3e-a8ab-a08f6ddfdeee.png)
If you open that .xf file and manually delete the last blank line, the protocol finishes

**Comment by pconesa** [comment]
all this was incredibly fast!! Well done!
