### ISSUE TITLE
exclude views

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-imod#199]
I'm trying to exclude some views,of my tilt series.

The original tilt series has 41 elements, and after the exclude views the tilt series still has the same number of elements. Perhaps, I am not using the exclude views properly, but seems pretty simple

![imagen](https://github.com/scipion-em/scipion-em-imod/assets/12271438/3d7d3a25-5631-4b58-af39-be1148688495)

![imagen](https://github.com/scipion-em/scipion-em-imod/assets/12271438/ed0a38fa-646a-4f6d-bcb7-d0399be8d6de)

**Comment by pconesa** [comment]
Vilas! Stack remains the same, and set information remains the same. TO verify it, open the tilt series set with the Tomoviewer

**Comment by azazellochg** [comment]
How can I know what did you put into exclude file?

**Comment by azazellochg** [comment]
Ah, just noticed the right part on the screenshot, sorry. Does you TS_ID match exactly what you put there?

**Comment by Vilax** [comment]
Sorry, I had to delete that example because of disk, but, I keep having trouble with it. 

![image](https://github.com/scipion-em/scipion-em-imod/assets/12271438/40aacc36-71c7-4842-9421-780e46b423bd)

In this case, I get an error. My guess is that the protocol expects a list of images to exclude, and it only provides one. could be this?

**Comment by azazellochg** [comment]
I can check this on the weekend, if anyone can do it earlier be my guest

**Comment by azazellochg** [comment]
@Vilax could you send me the tilt series sqlite that you are using as input?

**Comment by azazellochg** [comment]
@Vilax I still cannot reproduce your problem. I have made a small fix to remove empty lines / spaces. Please pull devel and try again

>  The TSID of ALL ts is mandatory.
This is not true. 

> the box for the text file should not be an advanced option
the reason for this is that by default, the protocol will remove disabled tilt images from the input TS. Alternatively, you can provide a text file with a list of tilts to exclude (advanced option).

**Comment by Vilax** [comment]
Thanks @azazellochg 

I've checked the empty lines issue and it works properly :) 

Unfortunately, I still believe that all TSIDs must appear in the exclude views text file. If they do not appear the protocol fails. My feeling is that the protocol expects a view to exclude, and that view index is an empty list or an empty array or something. And the list cannot be empty. See the error of my second post

**Comment by Vilax** [comment]
@azazellochg 

I've fixed the issue, you can see the PR here:

https://github.com/scipion-em/scipion-em-imod/pull/201
