### ISSUE TITLE
imod binning of tilt series and tomograms with a non-integer binning factor gives wrong metadata 

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-imod#200]
Hello
imod doesn't allow binning with a non-integer factor, but what is happening in scipion if the binning factor is not an integer, is that the data (tilt series or tomogram) will be binned by only the integer part, but the metadata will have the new pixel size.
To reproduce the bug without much calculations, try binning by 1.25. The result is like in the screenshot below. There was no binning, but the pixel size has changed.
We probably better allow only integer as a binning factor. It is useful however to have another protocol that allows non-integer binning.

![image](https://github.com/scipion-em/scipion-em-imod/assets/45387413/090c8dd1-6076-467d-8ba3-0a747b09c5d3)

**Comment by pconesa** [comment]
Thanks Mohamad, probably we weren't aware of this.
