### ISSUE TITLE
fiducial alignment and CTF correction do not store the proper dose per image

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-imod#202]
Here is an example with the fiducial alignment. Similarly occurs with the CTF correction

![image](https://github.com/scipion-em/scipion-em-imod/assets/12271438/01e894e7-7c86-4862-b3c6-1cc3ed9d99c2)

**Comment by Vilax** [comment]
Fixed here: https://github.com/scipion-em/scipion-em-imod/pull/203

**Comment by azazellochg** [comment]
Is CTF case fixed as well?

**Comment by Vilax** [comment]
Yes, it is. The problem with the CTF correction was that previous protocol
(the alignment) had no the proper dose. It was domino effect.
