### ISSUE TITLE
Imod -Fiducial alignemnt interpolated with TM

### ISSUE THREAD

**Issue by fede-pe** [scipion-em/scipion-em-imod#214]
For some reason, the output interpolated output set of tilt series at Imod -Fiducial alignment has also an associated TM. This is nonsense since its applying a transformation to something aligned, spoiling the posterior reconstruction.

**Comment by fede-pe** [comment]
Extend this problem also to imod -apply transform

**Comment by fede-pe** [comment]
I think the error is a new behaviour in the copyInfo method

**Comment by pconesa** [comment]
You are right.....copyinfo was modified recently and has now introduced this bug.
