### ISSUE TITLE
Imod should convert the input files to MRC if the input files are in a non compatible format

### ISSUE THREAD

**Issue by JorMaister** [scipion-em/scipion-em-imod#216]
We can import tomograms or TS in file formats that crash IMOD, such as HDF. The plugin should always check if the file formats are compatible with the program they wrap and, if not, convert them to a compatible one.

**Comment by rdrighetto** [comment]
IMOD supports HDF files, so perhaps the issue is something more specific?

--
Ricardo Diogo Righetto


Em qui., 21 de set. de 2023 às 13:15, Jorge Jiménez de la Morena <
***@***.***> escreveu:

**Comment by JorMaister** [comment]
You are right, it seems to be a problem from the plugin side. Thanks, @rdrighetto
