### ISSUE TITLE
Review imod CTF correction with excluded views

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-imod#246]
A mismatch in the number of items has been reported when views are excluded.

NOTE: This is triggered because we cannot import aretomo ctf (cistemlike) aretomo files that only have ctf lines for the non excluded views. If we tolerate this we will have "partial ctf sets" (ctf missing fo the excused views) that should work in later prcesses

**Comment by JorMaister** [comment]
Solved
