### ISSUE TITLE
Error in imod -fiducial alignment

### ISSUE THREAD

**Issue by Vilax** [scipion-em/scipion-em-imod#27]
Dear scipioners,

I obtained the next error in fiducial alignment, it makes reference to a scipion file of hte tomo plugin. I think it is a code error, but perhaps it is in the data.

01272:   STARTED: computeOutputModelsStep, step 8, time 2020-09-03 12:01:56.416307
01273:   Traceback (most recent call last):
01274:     File "/home/vilas/opt/scipion3_test/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
01275:       self._run()
01276:     File "/home/vilas/opt/scipion3_test/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 239, in _run
01277:       resultFiles = self._runFunc()
01278:     File "/home/vilas/opt/scipion3_test/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 235, in _runFunc
01279:       return self._func(*self._args)
01280:     File "/home/vilas/opt/scipion3_test/.scipion3env/lib/python3.7/site-packages/imod/protocols/protocol_fiducialAlignment.py", line 512, in computeOutputModelsStep
01281:       fiducialGapResidList = utils.formatFiducialResidList(landmarkModelGapsResidPath)
01282:     File "/home/vilas/opt/scipion3_test/.scipion3env/lib/python3.7/site-packages/imod/utils.py", line 103, in formatFiducialResidList
01283:       vector[4]])
01284:   IndexError: list index out of range
01285:   Protocol failed: list index out of range
01286:   FAILED: computeOutputModelsStep, step 8, time 2020-09-03 12:01:56.461133
01287:   *** Last status is failed

**Comment by fede-pe** [comment]
This problem should be fixed with the last release of this plug-in. Please refresh your repository and restart the protocol. If the problem persists add the protocol execution form and the dataset used if possible.
