### ISSUE TITLE
Tilt-series preprocess odd/even problem with excluded views

### ISSUE THREAD

**Issue by wlugmayr** [scipion-em/scipion-em-imod#275]
When going over the June 2024 tomo tutorial I realized that in this step 'Advanced -> Apply to odd/even Yes' does not work for the odd/even stacks (after step Exclude views - 1):

$ header Runs/000470_ProtImodTSNormalization/extra/TS_03/TS_03_odd.mrcs | grep Number
 Number of columns, rows, sections .....     928     960      41
$ header Runs/000470_ProtImodTSNormalization/extra/TS_03/TS_03_even.mrcs | grep Number
 Number of columns, rows, sections .....     928     960      41
$ header Runs/000470_ProtImodTSNormalization/extra/TS_03/TS_03.mrcs | grep Number 
 Number of columns, rows, sections .....     928     960      40

This leads later in task  CTF correction - Advanced - Correct odd/even to problems with 40 vs. 41 lines.

**Comment by azazellochg** [comment]
Which plugin version do you have? Devel has had a lot of changes since the last release, including handling excluded views. I suggest you try it with devel plugin installation or wait for the next release with many bugfixes.

**Comment by azazellochg** [comment]
I'll go through the tutorial with even/odd this weekend to check anyway.

**Comment by wlugmayr** [comment]
This instance will only get stable plugins since its targeted to normal users. I updated scipion and the plugins at the beginning of this week.
scipion-em-imod                3.4.1      [X]

**Comment by azazellochg** [comment]
I see. Unfortunately, imod plugin updates haven't been released in a long time, sorry about that.

**Comment by wlugmayr** [comment]
No need to be sorry, only selected users see this instance until the official switch to RHEL9 end of this month. The problem with the current CentOS7 Scipion instance was lots of devel plugins. So after each update some things were working or not working anymore This confused the users and they stopped using Scipion. So this time only stable plugins on the main cluster instance ;-)

**Comment by rdrighetto** [comment]
Interesting, our experience is quite the opposite: by sticking to stable
plugins only, things are often broken or outdated. So for the best
experience we have all (tomo) plugins in devel. It's true that in devel
things change very often, but it's usually for the better.

--
Ricardo Diogo Righetto


Em sex., 14 de jun. de 2024 às 12:13, wlugmayr ***@***.***>
escreveu:

**Comment by azazellochg** [comment]
well it depends very much on the local IT policy

**Comment by azazellochg** [comment]
@wlugmayr I had a look, excluded views are still work in progress so this is not working. odd/even adds another layer of complexity on top and will need more work

**Comment by JorMaister** [comment]
Solved
