### ISSUE TITLE
CTF correction step: generating defocus file failed

### ISSUE THREAD

**Issue by wlugmayr** [scipion-em/scipion-em-imod#276]
When going over the June 2024 tutorial (2D CTF correction) using CTF auto on 40 frames:

stdout.log
00097:   FINISHED: convertInputStep, step 1, time 2024-06-14 10:20:04.623320
00098:   STARTED: generateDefocusFile, step 2, time 2024-06-14 10:20:04.638512
00099:   Trying to generate defocus file at Runs/001922_ProtImodCtfCorrection/tmp/TS_03/TS_03.defocus
00100:   FAILED: generateDefocusFile, step 2, time 2024-06-14 10:20:04.652169

stderr.log
00001:   Traceback (most recent call last):
00002:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 203, in run
00003:       self._run()
00004:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 254, in _run
00005:       resultFiles = self._runFunc()
00006:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 250, in _runFunc
00007:       return self._func(*self._args)
00008:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/imod/protocols/protocol_ctfCorrection.py", line 173, in generateDefocusFile
00009:       utils.generateDefocusIMODFileFromObject(ctfTomoSeries, defocusFilePath, inputTiltSeries=ts)
00010:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/imod/utils.py", line 665, in generateDefocusIMODFileFromObject
00011:       defocusUDict = generateDefocusUDictionary(ctfTomoSeries)
00012:     File "/gpfs/cssb/software/rhel9/x86_64/scipion/3.x/miniconda/envs/scipion3/lib/python3.8/site-packages/imod/utils.py", line 860, in generateDefocusUDictionary
00013:       index = ctfTomo.getIndex().get()
00014:   AttributeError: 'int' object has no attribute 'get'
00015:   Protocol failed: 'int' object has no attribute 'get'

**Comment by azazellochg** [comment]
Thanks @wlugmayr , this has been fixed in devel branch and just waiting to be released.

**Comment by wlugmayr** [comment]
Well does not really fit here, but when I was searching if the error comes from myself I realized that the recent June 2024 tutorial is not consistent.
Once the input was
imod - Automatic CTF estimation.CTFTomoSeries
and later (now correct):
imod - CTF estimation (auto).CTFTomoSeries
So I was not sure if I did the right thing and maybe future readers are also uncertain if they have choosen the right CTF task.

**Comment by azazellochg** [comment]
I see, thanks. I'll update the picture in the tutorial

**Comment by azazellochg** [comment]
Done! New pdf should appear on the website soon. Otherwise,
[Scipion_Tutorial_Tomogram_Reconstruction.pdf](https://github.com/user-attachments/files/15858072/Scipion_Tutorial_Tomogram_Reconstruction.pdf)
