### ISSUE TITLE
why are IMOD_DIR IMOD_PATH cleared?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [scipion-em/scipion-em-imod#284]
https://github.com/scipion-em/scipion-em-imod/blob/f3efd176a9ca15d9c8b4a0c02e96bc4cd97ade8e/imod/__init__.py#L85

I have defined IMDO_DIR to point to a proper IMOD installation path, but scipion plugin is ignoring it.

**Comment by azazellochg** [comment]
Because Scipion uses IMOD_HOME to find where IMOD is.
