### ISSUE TITLE
Symbolic links are broken when defining SCIPION_SCRATCH

### ISSUE THREAD

**Issue by oierlauzi** [scipion-em/scipion-em-imod#296]
When running X-rays eraser, protocol fails if `SCIPION_SCRATCH` is defined. The reason behind this is that the `tmp` directory in the protocol is a symbolic link to a folder inside `SCIPION_SCRATCH`. X-rays eraser creates a **relative symbolic link inside the `tmp` directory**. It turns out that relative symbolic links evaluate relative to `SCIPION_SCRATCH` instead of the project directory. 

**How to replicate the issue:**

1. Define `SCIPION_SCRATCH` to whatever directory in `scipion.conf`
2. Launch scipion
3. Launch imod - X eraser protocol with whichever TS
4. Observe errors in stdout related to image files not existing. In addition, when setting one of the TS directories inside `tmp` as CWD and listing the grand-parent directory (`ls ../../../`) you will observe that it points to `SCIPION_SCRATCH` instead of the project directory.

I would suggest using absolute links inside `tmp`, as relative links may be broken in certain scenarios. Due to the transient nature of `tmp`, this does not cull project portability.

**Comment by azazellochg** [comment]
I would not recommend using SCIPION_SCRATCH for anything, as unfortunately, almost none of the plugins have been tested with this setting for tmp folder.

**Comment by pconesa** [comment]
Oier is among those using it and solving his problems.... so probably we just need to be make xray compatible with our basic scratch setup.
________________________________
De: Grigory Sharov ***@***.***>
Enviado: miércoles, 25 de septiembre de 2024 13:53
Para: scipion-em/scipion-em-imod ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: Re: [scipion-em/scipion-em-imod] Symbolic links are broken when defining SCIPION_SCRATCH (Issue #296)


I would not recommend using SCIPION_SCRATCH for anything, as unfortunately, almost none of the plugins have been tested with this setting for tmp folder.

**Comment by oierlauzi** [comment]
Maybe this is not the place for this debate. In any case, I think that the `SCIPION_SCRATCH` implementation _per-se_ is very elegant and robust (Simply creates a sufficiently unique directory and symlinks it). I think that it has potential for automatizing and handling the scratch directory for programs that need it without colliding with each other. 

Thus, I consider that bugs related to its handling in protocols should be fixed, instead of moving towards deprecating the scratch option. I offer myself to fix these issues.

**Comment by azazellochg** [comment]
Of course, I'm not against fixing this :) just saying that it is at the bottom of my priority list. PRs are welcome

**Comment by pconesa** [comment]
Don't worry. We will help with this. Actually, imod plugin is a "multi owner" plugin. 😉
________________________________
De: Grigory Sharov ***@***.***>
Enviado: jueves, 26 de septiembre de 2024 9:58
Para: scipion-em/scipion-em-imod ***@***.***>
Cc: Pablo Conesa ***@***.***>; Comment ***@***.***>
Asunto: Re: [scipion-em/scipion-em-imod] Symbolic links are broken when defining SCIPION_SCRATCH (Issue #296)


Of course, I'm not against fixing this :) just saying that it is at the bottom of my priority list. PRs are welcome
